apiVersion: v1
kind: ReplicationController
metadata:
  name: zomato-rc
spec:
  replicas: 3
  selector:
    app: zomato-app #must match with pod labels
  template:
    metadata:
      name: zomato-pod
      labels:
        app: zomato-app #pod label
    spec:
      containers:
        - name: zomato-container
          image: kastrov/zomato
          ports:  
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: LoadBalancer
  selector:
    app: zomato-app
  ports:
    - port: 80
      targetPort: 3000
      