apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: swiggy-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swiggy-app
  template:
    metadata:
      name: swiggy-pod
      labels:
        app: swiggy-app
    spec:
      containers:
        - name: swiggy-container
          image: kastrov/swiggy
          ports:
           - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: swiggy-service
spec:
  type: LoadBalancer
  selector:
    app: swiggy-app
  ports:
    - port: 80
      targetPort: 3000

        
        