apiVersion: v1
kind: Pod
metadata:
  name: zomato-pod
  labels:
    app: zomato
spec:
  containers:
    - name: zomato-container
      image: kastrov/zomato
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: zomato-service
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
    - port: 80
      targetPort: 3000
